### ISSUE TITLE
Is boost really necessary?

### ISSUE THREAD

**Issue by apfeltee** [trailofbits/pe-parse#24] opened 2016-09-22 23:58 UTC
Looking at the source code, I fail to see where the need for the boost dependency is.  
For instance, `boost/cstdint.hpp`  could be literally replaced by just `cstdint`, which is the C++ header of `stdint.h`.  

As for `boost::to_upper`, it could be replaced by `std::transform(str.begin(), str.end(),str.begin(), ::toupper)`, which would have the exact same effect. (Also, in C++, stdlib functions are required by the standard to be actual functions, and not just macros like it is the case in C).

Removing boost, unless it's really, absolutely necessary, would probably be a good idea.

**Comment by dguido** [comment] 2017-03-03 16:47
Dupe of #10

**Closed by dguido** 2017-03-03 16:47 UTC
